// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Article {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  cover_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  body?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Information {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  body?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface LegalPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  body?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Menu {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  describe?: string;
  category: "Wisky" | "Food" | "Sweets" | "Beer" | "Original Cocktail" | "Cocktail" | "Non-Alcohol";
  price?: string;
  order: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ShopInfo {
  id: string;
  slug: string | null;
  status: string;
  store_name: string;
  tel: string;
  tel_no: string;
  working_time: string;
  contact_time: string;
  break_week_day: string;
  seats?: string;
  reservation?: string;
  postal_code: string;
  address_level1: string;
  address_level2: string;
  address_line1: string;
  address_line2?: string;
  map_embed_url?: string;
  golf_url?: string;
  online_shop_url?: string;
  instagram?: string;
  facebook?: string;
  line?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    articles: Article;
    information: Information;
    legal_pages: LegalPage;
    menus: Menu;
    shop_info: ShopInfo;
  }
}